# Generated by Django 5.2.6 on 2025-09-14 12:07

import taskify_auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskify_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', taskify_auth.models.CustomUserManager()),
            ],
        ),
    ]
