# Generated by Django 5.2.6 on 2025-09-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskify_auth', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
