# Generated by Django 5.2.6 on 2025-10-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskify_auth', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
