# Generated by Django 5.2.6 on 2025-11-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskify_auth', '0004_customuser_locked_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='locked_at',
        ),
    ]
