# Generated by Django 5.2.6 on 2025-10-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskify_core', '0002_alter_team_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
