# Generated by Django 5.2.6 on 2025-10-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskify_core', '0004_userlockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='is_kicked',
            field=models.BooleanField(default=False),
        ),
    ]
